# create a docker-compose for local devlopment

# services: define each component as service
# volumes: persistent storage for DB data
# environment variables: pass config/secretes
# scaling: run multiple backend instances

version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/todo
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge